{{- if .Values.mqttAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kermi2mqtt.mqttSecretName" . }}
  labels:
    {{- include "kermi2mqtt.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mqttAuth.usernameKey }}: {{ .Values.mqttAuth.username | b64enc | quote }}
  {{ .Values.mqttAuth.passwordKey }}: {{ .Values.mqttAuth.password | b64enc | quote }}
{{- end }}
